#pragma once

#include <memory>
#include <string>
#include <thread>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "icon/hal/hardware_module_interface.h"
#include "icon/hal/hardware_interface_handle.h"
#include "icon/hal/hardware_module_runtime.h"
#include "icon/hal/realtime_clock.h"
#include "icon/interprocess/remote_trigger/remote_trigger_server.h"
#include "icon/interprocess/shared_memory_lockstep/shared_memory_lockstep.h"
#include "icon/interprocess/shared_memory_manager/domain_socket_server.h"
#include "icon/interprocess/shared_memory_manager/shared_memory_manager.h"
#include "icon/utils/attributes.h"
#include "icon/utils/log.h"
#include "icon/utils/mutex.h"

// Generated by flatc
#include "flatbuffer_definitions/icon/hal/interfaces/joint_command.fbs.h"
#include "flatbuffer_definitions/icon/hal/interfaces/joint_state.fbs.h"
#include "flatbuffer_definitions/icon/hal/interfaces/hardware_module_state.fbs.h"
#include "flatbuffer_definitions/icon/hal/interfaces/icon_state.fbs.h"

#include "controller_manager_msgs/srv/set_hardware_component_state.hpp"
#include "controller_manager_msgs/srv/switch_controller.hpp"
#include "icon_hwm_controller_msgs/msg/hardware_module_state.hpp"

// Generated by generate_parameter_library
#include "icon_hwm_controller/icon_hwm_controller_parameters.hpp"

#include "realtime_tools/realtime_publisher.hpp"

namespace icon_hwm_controller
{

class IconHwmController final : public controller_interface::ControllerInterface {
public:
  IconHwmController();

  // controller_interface::ControllerInterface
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_init() override;
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_cleanup(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(
    const rclcpp::Time & time,
    const rclcpp::Duration & period) override;

private:
  intrinsic::log::Logger logger_;
  // Clock Driver
  std::unique_ptr<intrinsic::RealtimeClock> clock_;
  // Once initialized, this holds raw pointers to `clock_` and `logger_`, so it must outlive those two.
  std::unique_ptr<intrinsic::icon::HardwareModuleRuntime> hwm_runtime_;
  // Parameters
  std::unique_ptr<ParamListener> param_listener_;
  Params params_;

  rclcpp::Publisher<icon_hwm_controller_msgs::msg::HardwareModuleState>::SharedPtr
    hwm_state_publisher_;
  rclcpp::TimerBase::SharedPtr publish_hwm_state_timer_;
  intrinsic::Mutex init_error_state_mutex_;
  std::optional<icon_hwm_controller_msgs::msg::HardwareModuleState> init_error_state_ INTR_GUARDED_BY(init_error_state_mutex_);

  void PublishCurrentHwmState();
};

}
