#pragma once

#include <memory>
#include <string>
#include <thread>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "icon/hal/hardware_module_interface.h"
#include "icon/hal/hardware_interface_handle.h"
#include "icon/interprocess/shared_memory_manager/domain_socket_server.h"
#include "icon/interprocess/shared_memory_manager/shared_memory_manager.h"

// Generated by flatc
#include "flatbuffer_definitions/icon/hal/interfaces/joint_command.fbs.h"
#include "flatbuffer_definitions/icon/hal/interfaces/joint_state.fbs.h"
#include "flatbuffer_definitions/icon/hal/interfaces/hardware_module_state.fbs.h"
#include "flatbuffer_definitions/icon/hal/interfaces/icon_state.fbs.h"

#include "icon/hal/realtime_clock.h"
#include "icon/interprocess/remote_trigger/remote_trigger_server.h"
#include "icon/interprocess/shared_memory_lockstep/shared_memory_lockstep.h"
#include "icon/utils/log.h"

#include "controller_manager_msgs/srv/set_hardware_component_state.hpp"
#include "controller_manager_msgs/srv/switch_controller.hpp"

// Generated by generate_parameter_library
#include "icon_hwm_controller/icon_hwm_controller_parameters.hpp"

#include "realtime_tools/realtime_publisher.hpp"
#include "icon_hwm_controller_msgs/msg/hardware_module_state.hpp"

namespace icon_hwm_controller
{

class IconHwmController final : public controller_interface::ControllerInterface,
  public intrinsic::icon::HardwareModuleInterface {
public:
  IconHwmController();

  // controller_interface::ControllerInterface
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_init() override;
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_cleanup(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(
    const rclcpp::Time & time,
    const rclcpp::Duration & period) override;

  // intrinsic::icon::HardwareModuleInterface
  intrinsic::Status Init() override {return intrinsic::OkStatus();}
  intrinsic::Status Prepare() override;
  intrinsic::RealtimeStatus Activate() override;
  intrinsic::RealtimeStatus Deactivate() override;
  intrinsic::Status EnableMotion() override;
  intrinsic::Status DisableMotion() override;
  intrinsic::Status ClearFaults() override;
  intrinsic::Status Shutdown() override;
  intrinsic::RealtimeStatus ReadStatus() override;
  intrinsic::RealtimeStatus ApplyCommand() override;

private:
  // Parameters
  std::unique_ptr<ParamListener> param_listener_;
  Params params_;

  // Shared Memory
  std::unique_ptr<intrinsic::icon::SharedMemoryManager> shm_manager_;
  std::unique_ptr<intrinsic::icon::DomainSocketServer> domain_socket_server_;
  intrinsic::icon::HardwareInterfaceHandle<intrinsic_fbs::IconState> icon_state_;
  intrinsic::icon::MutableStrictHardwareInterfaceHandle<intrinsic_fbs::JointPositionState>
  joint_position_state_;
  intrinsic::icon::MutableStrictHardwareInterfaceHandle<intrinsic_fbs::JointVelocityState>
  joint_velocity_state_;
  intrinsic::icon::StrictHardwareInterfaceHandle<intrinsic_fbs::JointPositionCommand>
  joint_position_command_;
  intrinsic::icon::MutableHardwareInterfaceHandle<intrinsic_fbs::HardwareModuleState>
  hardware_module_state_;

  // Remote Trigger Servers
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> prepare_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> activate_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> deactivate_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> enable_motion_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> disable_motion_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> clear_faults_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> shutdown_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> read_status_server_;
  std::unique_ptr<intrinsic::icon::RemoteTriggerServer> apply_command_server_;

  std::jthread state_change_query_thread_;

  // Clock Driver
  std::unique_ptr<intrinsic::RealtimeClock> clock_;

  // Service Clients
  rclcpp::Client<controller_manager_msgs::srv::SwitchController>::SharedPtr
    switch_controller_client_;
  rclcpp::Client<controller_manager_msgs::srv::SetHardwareComponentState>::SharedPtr
    set_hw_state_client_;

  // Internal state
  uint64_t cycle_counter_ = 0;
  std::atomic<intrinsic_fbs::StateCode> state_code_{intrinsic_fbs::StateCode::kDeactivated};
  std::atomic<bool> stop_requested_{false};

  intrinsic::RealtimeStatus fault_status_ = intrinsic::RtOkStatus();
  bool want_to_publish_state_ = false;
  std::shared_ptr<realtime_tools::RealtimePublisher<icon_hwm_controller_msgs::msg::HardwareModuleState>> state_publisher_;

  intrinsic::log::Logger logger_;

  enum class EnableState : uint8_t {
    kUnknown,
    kEnabling,
    kEnableSucceeded,
    kEnableFailed
  };

  enum class DisableState : uint8_t {
    kUnknown,
    kDisabling,
    kDisableSucceeded,
    kDisableFailed
  };

  // This is a shared pointer because we refer to it from service response
  // callbacks. If one of those remains in-flight after the IconHwmController is
  // destroyed, we don't want it to access a dangling reference.
  //
  // (Yes, the Node that is responsible for invoking callbacks is a member of
  // this class, so it too should be cleaned up by the destructor and not invoke
  // any more callbacks after that, but it's a member from a *base* class, so
  // the destructor that cleans it up runs after the one that cleans up the
  // direct members, like `enable_state_`.
  std::shared_ptr<std::atomic<EnableState>> enable_state_;
  static_assert(std::atomic<EnableState>::is_always_lock_free);
  std::atomic<DisableState> disable_state_;
  static_assert(std::atomic<DisableState>::is_always_lock_free);

  // Helper methods
  void DetectFaults();
  void UpdateHwmState();
  intrinsic::RealtimeStatus SetStateDirectly(
      intrinsic_fbs::StateCode state,
      intrinsic::RealtimeStatus fault_status = intrinsic::RtOkStatus(),
      bool force = false,
      bool silent = false);
  intrinsic::Status CallSwitchController(
    const std::vector<std::string> & activate,
    const std::vector<std::string> & deactivate);
  // Sets the state for the given ROS2 HardwareComponent to `state`.
  intrinsic::Status CallSetHwState(const std::string & name, uint8_t state);
};

}
