services:
  ur_ros2_icon_hwm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ur_ros2_icon_hwm
    image: ur_ros2_icon_hwm:latest
    tty: true
    entrypoint: ["/bin/bash", "-c", "source ./install/setup.bash && exec \"$@\"", "--"]
    command: >
      colcon test --packages-up-to ur_ros2_icon_hwm
        --event-handlers console_direct+ &&
      colcon test-result --all
