# proto-file: intrinsic/assets/services/proto/service_manifest.proto
# proto-message: intrinsic_proto.services.ServiceManifest

metadata {
  id {
    package: "ai.intrinsic"
    name: "fanuc_ros2_icon_hwm"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "FANUC ROS 2 Control Hardware Module."
  }
  display_name: "FANUC ROS 2 HWM"
}
