FROM ros:kilted-ros-core
RUN apt-get update && apt-get install -y ros-kilted-xacro ros-kilted-backward-ros python3-filelock ros-kilted-ros2-control ros-kilted-ros2-controllers ros-kilted-robot-state-publisher && rm -rf /var/lib/apt/lists/*
ENV HOME=/tmp
