load("//google3/bazel:cc_macros.bzl", "cc_library")

cc_library(
    name = "realtime_annotations",
    hdrs = ["realtime_annotations.h"],
    visibility = [
        "//incode/icon/no_absl:__subpackages__",
    ],
)
