services:
  icon_hwm_controller:
    build:
      args:
        - AMENT_WORKSPACE_DIR=/ament_ws
        - ROS_BASE_IMAGE=ros:kilted-ros-base
      context: ../..
      dockerfile: icon_hwm_controller/docker/Dockerfile
      target: base
    container_name: icon_hwm_controller
    image: icon_hwm_base:latest
    tty: true
    entrypoint: ["/bin/bash", "-c", "source ./install/setup.bash && exec \"$@\"", "--"]
    command: >
      colcon test --packages-up-to icon_hwm_controller
        --event-handlers console_direct+ &&
      colcon test-result --all
