# proto-file: google/protobuf/any.proto
# proto-message: google.protobuf.Any

[type.googleapis.com/intrinsic_proto.icon.HardwareModuleConfig] {
  drives_realtime_clock: true
  control_frequency_hz: 500.0
  module_config {
    [type.googleapis.com/intrinsic_proto.services.Ros2HwmConfig] {
      launch_package: "ur_ros2_icon_hwm"
      launch_file: "ur_control.launch.py"
      launch_parameters {
        key: "hwm_name"
        value: "ur_hwm"
      }
      launch_parameters {
        key: "ur_type"
        value: "ur5e"
      }
      launch_parameters {
        key: "robot_ip"
        value: "192.170.10.100"
      }
      icon_hwm_controller_config {
        lock_memory: true
        shm_namespace: ""
        realtime_priority_low: 40
        realtime_priority_high: 45
      }
    }
  }
}
