/**:
  ros__parameters:
    update_rate: $(var control_frequency)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    fanuc_gpio_controller:
      type: fanuc_controllers/FanucGPIOController

    lock_memory: $(var lock_memory)
    cpu_affinity: $(var cpu_affinity)
    thread_priority: $(var realtime_priority_low)

/**/fanuc_gpio_controller:
  ros__parameters:
    gpio_config_file_package: $(var gpio_config_package)
    gpio_config_file_path: $(var gpio_config_path)

/**/icon_controller:
  ros__parameters:
    type: icon_hwm_controller/IconHwmController
    name: "$(var hwm_name)"
    context_name: "$(var context_name)"
    shm_namespace: "$(var shm_namespace)"
    lock_memory: $(var lock_memory)
    cpu_affinity: $(var cpu_affinity)
    realtime_priority_low: $(var realtime_priority_low)
    realtime_priority_high: $(var realtime_priority_high)
    drives_realtime_clock: $(var drives_realtime_clock)
    control_frequency_hz: $(var control_frequency_hz)
    dof_names:
      - "$(var prefix)J1"
      - "$(var prefix)J2"
      - "$(var prefix)J3"
      - "$(var prefix)J4"
      - "$(var prefix)J5"
      - "$(var prefix)J6"
    command_interfaces:
      - position
    reference_and_state_interfaces:
      - position
      - velocity
    hardware_component_name: "$(var robot_model)"
    operational_status_topic: /operational_status
    clear_faults_trigger_service: /clear_faults